### ISSUE TITLE
Fatal error when playing in the editor - UE 5.3.0 and 5.3.2

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#77]
**Modifying issue to UE 5.3.0 only, it works + Fatal error.
5.3.2 doesn't build, so makes no sense to ask for it if 5.3.0 works perfect in the headset.
This happens in the Epic games Build 5.3.2 and in the Oculus Build 5.3.0 and 5.3.2** 

I've been trying to build in the latest build 5.3 and I have the following problems:
- Fatal error when trying to play the editor (more details in my previous Issue, I have the same problem here)
- PLUS: Can't build the apk, Build error appears at the end of everything with no details, it build everything apparently without errors, except that at the end of all, even after the "BUILD SUCESSFULL" in the log) says something about the Blink Audio, when I changed that to PCM, or platform specific, it has less details and build fail at the end anyways. 
- When loading the Engine, the following warning appears: 
-         The 'OculusXR' plugin was designed for build 5.3.0. Attempt to load it anyway? (When I try the Meta XR SDK from the web, nothing appears if I use the one included in the build)
-         The 'OculusPlatform' plugin was designed for build 5.3.0. Attempt to load it anyway?
-         The 'VisualStudioTools' plugin was designed for build 5.3.0. Attempt to load it anyway?

In this case (Custom Build Oculus-UE 5.3.2 I can't play in the editor, and I can't build the apk) 
I tried every possible combination of setups, W10, W11, VS Pro, VS community, Android 12, Android 13 (latest).

I'm using NDK n25b/JDK 11.0.2/SDK API latest/ NDKAPI android-29
In UE 5.3.0 the build works, with the problem in the editor but the apk works in standalone. 

Thanks!

**Comment by jasonmeisel** [comment]
This should be solved by the latest change (197f26ea6845b5f49dad6f840e909b280a6b0db5). If this resolves the issue for you, please let us know and close the issue.

**Comment by alefriant** [comment]
I'll try it and will let you know, thanks!

**Comment by alefriant** [comment]
Hi @jasonmeisel 
- The message about the plugins designed for 5.3.0 is ok. I changed the code to 5.3.2 anyways because the "" didn't work. 
- My main concern is the Fatal error when launching the Sharedspaces in the Unreal Editor and that wasn't solved. I tried the last revision of SharedSpaces + the last revision of UE 5.3.2 from Oculus/GitHub. I didn't modified nothing at all. Was an entirely clean instalation with no external asset or configuration. This happens in single player, multiplayer. I really need this feature to test my characters in the pc which has been really useful until a few weeks when this stopped working. Basically the 3rd character pc is not functional at all. Attached are some pictures of the sharedspaces and my file. 
![FatalError 2](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/84304509/4dadd78f-3398-421b-affe-b08e34a0573e)
![FatalError_SharedSpaces](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/84304509/297e02f2-a8c1-402d-a1e6-971001988954)
![FatalError_SharedSpaces_3](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/84304509/1d492827-15cb-4598-9a7f-ed467ccb8608)

**Comment by alefriant** [comment]
@jasonmeisel 
This happens in the UE 5.3.0 build from Oculus, in the UE 5.3.2 build from Oculus and in UE5.3.2 from Epic games, the same fatal error when trying to run sharedspaces at the viewport.
Notes: 
When I run the UE 3rd person C++ template this doesn't happens. 
When I compile the Sharedspaces file (5.3.0 only) and run it in the headset everything works fine in UE 5.3.0, in UE 5.3.2 I still having the same errors:
- Can't build the apk, Build error appears at the end of everything with no details, it build everything apparently without errors, except that at the end of all, even after the "BUILD SUCESSFULL" in the log) says something about the Blink Audio, when I changed that to PCM, or platform specific, it has less details and build fail at the end anyways.

**Comment by jasonmeisel** [comment]
> * The message about the plugins designed for 5.3.0 is ok. I changed the code to 5.3.2 anyways because the "" didn't work.

The message is actually what makes this problem frustrating. Looking into it, when you click "OK" to load the plugin, it only loads it in the Editor. When you go to cook or package a build, it will not include the plugin, which I believe is what is causing your build issues. The `EngineVersion` of the plugin must be null or match the version of the engine exactly.

I'm not sure why you are getting that fatal error when you play in Editor, though. Do you have logs from those runs?

**Comment by alefriant** [comment]
Hey @jasonmeisel For me I'm ok with the game in 5.3.0 thought... it's functional and I can't spend more time trying to fix the 5.3.2 build. (Unless you need some help I can try the brand new sharedspaces again and send you a log, but 5.3.0 is working ok in the headset)

Anyways I have the fatal error when running the viewport in the pc which is weird and as I mentioned that was a great feature to try replication, features and mechanics without the headset. 
- Considerations for the attached log:
1- This build runs perfect in the Oculus 2 and 3 in Standalone, replicated/multiplayer, I can travel between games and maps, use destinations, etc. Features like Application SpaceWarp (AppSW), Mobile Tonemap Subpass, OS Splash Screen, etc. are working perfect. 
2- The only problem I have here is when trying to play in the viewport (Windows, single or multiuser, doesn't matters, everything will crash, and I only need to play with the 3rd person UE robot)
3- This log starts when I opened the file, I immediately press Play and crash, I didn't do anything else. 
**[SharedSpaces_April3th_2024.txt](https://github.com/oculus-samples/Unreal-SharedSpaces/files/14847742/SharedSpaces_April3th_2024.txt)**

**_Again, Thanks for your time!_** and thanks for the tip about the OK to load the plugin not running in the build I didn't know about that. 



![image](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/84304509/0aeed894-d8ed-407a-b44a-fdf5132ef447)

**Comment by alefriant** [comment]
Hey @jasonmeisel !
Or the Meta team re-wired something behind scenes or Visual Studio 17.9.6 fixed something or the new update of Windows fixed something. But playing the game in pc is suddenly working again (only in Client mode as always did it before), I tested it today thinking in the first option, whatever it's working again, so thanks for your time. :) I'll finally will be able to delete the secondary 3rd person file I had in parallel for testing purposes 👍 
PS: I'll continue in 5.3.0 because it runs perfect. I have no time to continue testing 5.3.2 I don't need any feature from that .2 update. 

![image](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/84304509/da50ffc7-9a63-4bb0-b76a-8d05d71198e3)
